name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './backend/package-lock.json'
        
    - name: Backend Install & Prisma Generate
      working-directory: ./backend
      run: |
        npm install
        npx prisma generate
        
    # Eğer ileride test yazılırsa "npm test" adımı buraya eklenebilir.
    # - name: Backend Tests
    #   working-directory: ./backend
    #   run: npm test

    - name: Frontend Install & Build
      working-directory: ./frontend
      run: |
        npm install
        npm run build
